### PR TITLE
Make use of time.Until

### PR DESCRIPTION
**Pull request by muesli**
Use time.Until instead of manually subtracting timestamps.

### CODE REVIEW

**Comment by muesli** [comment]
Sorry, but I thought support for Go <1.8 was dropped recently?

**Comment by elithrar** [comment]
https://github.com/gorilla/websocket/releases/tag/v1.4.0

_prior_ to v1.7 - e.g. Go 1.6 and below 😄

**Comment by muesli** [comment]
You're right, I probably either read that wrong or simply didn't remember correctly. Not sure how you manage the project, but we could keep it open for a future review. I guess it'll become relevant again sooner than later :slightly_smiling_face:

**Comment by elithrar** [comment]
Not a bad point. We don’t have a pressing reason to drop 1.7 yet, and it’s
impossible to know how many users are on older versions*, but I’ll create a
label that can represent these kind of features/hold them open.

**Pull request closed without merging**
