### PR TITLE
make tests parallel

### PR DESCRIPTION
**Pull request by ninedraft**

### CODE REVIEW

**Comment by AlexVulaj** [comment]
@ninedraft do you have any benchmarks on how long tests took before and after this change? My intuition tells me that this project and its tests aren't large enough to see much benefit from parallelization, but if you have any data to suggest otherwise I'm open to considering it.

**Comment by GreenMarmot** [comment]
```
$ gh pr checkout 872
$ go test         # ensure that code is compiled to cache
$ time go test    # time test execution
go test  0.52s user 0.50s system 226% cpu 0.448 total
$ git checkout main
$ go test         # ensure that code is compiled to cache
$ time go test    # time test execution
go test  0.48s user 0.46s system 186% cpu 0.504 total
```

YMMV

**Comment by AlexVulaj** [comment]
@GreenMarmot if I'm seeing correctly, the tests run slower and take more CPU when run from this PR. For that reason I'm going to decline this change.

**Comment by AlexVulaj** [comment]
@GreenMarmot Deleted my comment as I think I misread the second half of your output. Let's go ahead and move forward with this.

**Review by AlexVulaj — APPROVED** [review]

**Pull request merged**
