### PR TITLE
add SetReadLimitFunc function

### PR DESCRIPTION
**Pull request by guonaihong**
I need to write a custom error, so I added this function(SetReadLimitFunc).

```golang
package main

import (
    "fmt"
    "github.com/gin-gonic/gin"
    "github.com/gorilla/websocket"
)

var upgrader = websocket.Upgrader{}

func main() {

    r := gin.Default()

    r.Any("/test", func(c *gin.Context) {
        r := c.Request
        w := c.Writer
        conn, err := upgrader.Upgrade(w, r, nil)
        if err != nil {
            return
        }

        defer conn.Close()

        conn.SetReadLimitFunc(300, func() {
            // write custom error
            conn.WriteMessage(websocket.TextMessage, []byte(`{"errmsg":"limit fail", "errcode": 1}`))
        })

        _, _, _ = conn.ReadMessage()
    })

    r.Run()
}

```

### CODE REVIEW

**Comment by guonaihong** [comment]
@elithrar This is a very simple feature, can you review the code?

**Comment by IngCr3at1on** [comment]
@guonaihong is there any way you can demonstrate the usage and functionality in a simple test case?

I agree it's simple but the nice thing about testing simple functionality is that it's usually relatively easy to test and having those tests helps ensure nothing is broken in the future.

**Comment by guonaihong** [comment]
Test file has been added

**Comment by FZambia** [comment]
Looks like when read limit reached [ErrReadLimit](https://github.com/gorilla/websocket/blob/master/conn.go#L90) returned from Read and NextReader methods - can't it be used to solve this case?

**Comment by guonaihong** [comment]
@FZambia The method you said is not working, please see the code below for the reason.

> https://github.com/gorilla/websocket/blob/master/conn.go#L865
>  
```go
c.readLength += c.readRemaining
if c.readLimit > 0 && c.readLength > c.readLimit {
        //Returning an error to the client
	c.WriteControl(CloseMessage, FormatCloseMessage(CloseMessageTooBig, ""), time.Now().Add(writeWait))
	return noFrame, ErrReadLimit
}
```

**Comment by FZambia** [comment]
@guonaihong yeah, I see now – misunderstood what you are trying to achieve. So you want to send a message to a client with a reason why request failed, right? Then maybe you can handle `CloseMessageTooBig` code on client side and react in a way you need?

**Comment by IngCr3at1on** [comment]
Thanks for the tests @guonaihong 

Had a look; I'm a little fuzzy on the use case as well but assuming for just a moment that it's useful anyway I decided to review the code regardless.

That said, LGTM but @elithrar must approve.

**Comment by guonaihong** [comment]
@FZambia I use the go websocket library development service, for many programming language clients, java, python, c#, nodejs, if you want each user to understand what the error code of websocket is, it is very difficult to operate, so you need to define the business error code. Errcode stores error codes, errmsg indicates error strings, easy to read, straightforward.

**Comment by srybacki** [comment]
When the limit is breached, this package writes a close message with the [RFC defined close code for message too big (code 1009)](https://tools.ietf.org/html/rfc6455#section-7.4.1). 

Standardize on the RFC.  If the websocket libraries for java, python, c#, nodejs  do not use the RFC defined code, then file an issue with those libraries to follow the RFC.  Application developers can consult the [RFC](http://tools.ietf.org/html/rfc6455#section-11.7) if they don't know the meaning of a code.

You can get the requested functionality without any change to the package: create a type similar to [io.LimitedReader](https://godoc.org/io#LimitedReader) that writes the message of your choice when the limit is breached.  Use this type to wrap the reader returned from NextReader.

People have criticized this package for its accumulated cruft.  This PR adds to that cruft.

**Comment by srybacki** [comment]
@elithrar @garyburd  I recommend rejecting this PR per my previous comments.

**Pull request closed without merging**
