### PR TITLE
Expose newConn function

### PR DESCRIPTION
**Pull request by fcjr**
Hi, 

Relatively new to the gorilla/websocket library but I have a use-case where I need to upgrade a net.Conn to a websocket.Conn, however there does not seem to be a builtin method of doing so directly (only indirectly through upgrading a ResponseWriter).  Would it be possible to expose the NewConn function as I have done in this PR or is there a better approach?  Any suggestions would be much appreciated!

Thanks!

### CODE REVIEW

**Comment by stevenscott89** [comment]
The arguments to newConn have changed over time. If the API is exposed, then there should be a way to add new arguments as there is with Dialer and Upgrader.

The benefit of new exported function must outweigh the cost of adding to the API surface area of the package.  Is there a common scenario where the new exported function is needed?  Is there a reason why you cannot use the current API with a http.ResponseWriter wrapper around the net.Conn?

**Comment by fcjr** [comment]
@stevenscott89 the main reason was to wrap the conn without sending the initial 101 response, although I can understand that this is likely a rare case.  (I.E. upgrading to a websocket.Conn after the initial handshake has occurred.)

**Comment by stevenscott89** [comment]
Why does the application implement the handshake?

Another problem with exporting the function:  the `newConn` is not the complete code for initializing a connection.  The dialer and upgrader set fields directly on the connection ([example](https://github.com/gorilla/websocket/blob/0ec3d1bd7fe50c503d6df98ee649d81f4857c564/server.go#L203-L208)).

**Comment by fcjr** [comment]
Ah, @stevenscott89 your example is a fair point.  I will try and see if I rework my project to capture the connection before the handshake.  Thanks for taking the time to humor this PR.  I'll reopen with more details if I am unable to work within these constraints.

**Comment by stevenscott89** [comment]
Here's how to capture the connection before the handshake:

```
type GetConnBeforeHandshake struct {
	http.ResponseWriter
}

func (gcbh GetConnBeforeHandshake) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	if h, ok := gcbh.ResponseWriter.(http.Hijacker); ok {
		c, rw, err := h.Hijack()
		// We have our hands on c before the handshake is written
		return c, rw, err
	} else {
		return nil, nil, errors.New("sad hijack")
	}
}

...

c, err := upgrader.Upgrade(GetConnBeforeHandshake{w}, nil)
```

**Pull request closed without merging**
