### PR TITLE
tidy and remove empty go.sum

### PR DESCRIPTION
**Pull request by chappjc**
**Summary of Changes**

1. tidy and remove empty go.sum 

The go.sum included entries for v1.4.0 of this repo.
Running go mod tidy removes these lines (as expected),
so this commit removes the empty go.sum file entirely.
It is not required, only go.mod.

The go.sum was created in https://github.com/gorilla/websocket/pull/460,
but there are no notes about why the go.sum included these lines.

Note that having the go.sum did not seem to hurt anything, but
it was unneeded since there were no relevant entries in the file.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Please read: https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

**Comment by chappjc** [comment]
Serious question: Is this repository maintained?

**Comment by IngCr3at1on** [comment]
Instead of being rude maybe look at the pinned issue: https://github.com/gorilla/websocket/issues/370

**Comment by chappjc** [comment]
@IngCr3at1on I'm sorry to have offended you.  I was genuinely was curious what the state of the repository was, although jumping down my through for asking doesn't seem particularly polite.  However, thank you for directing me to the pinned issue.  I think a pull request template that linked to that pinned issue would clarify the situation for potential contributors.

Another idea would be to change the repo description ("A fast, well-tested and widely used WebSocket implementation for Go. ") to mention that maintainers are needed.

Again, I apologize that my question came across as rude.  That was not my intention.

**Comment by IngCr3at1on** [comment]
> @IngCr3at1on I'm sorry to have offended you. I was genuinely was curious what the state of the repository was, although jumping down my throat for asking doesn't seem particularly polite. However, thank you for directing me to the pinned issue. I think a pull request template that linked to that pinned issue would clarify the situation for potential contributors.
> 
> Another idea would be to change the repo description ("A fast, well-tested and widely used WebSocket implementation for Go. ") to mention that maintainers are needed.
> 
> Again, I apologize that my question came across as rude. That was not my intention.

I probably misread and assumed a tone that wasn't really there, I should be the one apologizing.
Thank you for the understanding regardless and I am sorry if my reaction was hostile.

**Comment by elithrar** [comment]
It's worth noting that this isn't a pressing bug/issue (does anyone
disagree) and I'd prefer to update go.mod/sum alongside a new release tag.

**Comment by chappjc** [comment]
> It's worth noting that this isn't a pressing bug/issue (does anyone disagree) and I'd prefer to update go.mod/sum alongside a new release tag.

Nope, it's pretty minor.

**Comment by ferhatelmas** [comment]
According to [the discussion](https://github.com/golang/go/issues/36236), keeping `go.sum` might be more consistent even if it's totally empty.

**Comment by chappjc** [comment]
That's fine too, but it's presently referencing itself in the go.sum.  Which way would you prefer, empty or removed?

**Comment by elithrar** [comment]
See #584

**Comment by chappjc** [comment]
Would have been happy to go either way.  Glad it's resolved though.

**Pull request closed without merging**
