### PR TITLE
Dialer: add optional method NetDialTLSContext

### PR DESCRIPTION
**Pull request by lluiscampos**
Fixes issue: https://github.com/gorilla/websocket/issues/745

With the previous interface, NetDial and NetDialContext were used for
both TLS and non-TLS TCP connections, and afterwards TLSClientConfig was
used to do the TLS handshake.

While this API works for most cases, it prevents from using more advance
authentication methods during the TLS handshake, as this is out of the
control of the user.

This commits introduces another a new dial method, NetDialTLSContext,
which is used when dialing for TLS/TCP. The code then assumes that the
handshake is done there and TLSClientConfig is not used.

This API change is fully backwards compatible and it better aligns with
net/http.Transport API, which has these two dial flavors. See:
https://pkg.go.dev/net/http#Transport

### CODE REVIEW

**Comment by lluiscampos** [comment]
The first commit is unrelated to the issue at hand, but otherwise the CI was failing on `gofmt` for latest Go version 1.17.

**Comment by garyburd** [comment]
- Remove DialTLS field.  The corresponding field in net/http Transport is deprecated, so there's no need to add it here.
- Convert map of tests to slice of tests for consistency with other tests.

```
	tests := []struct {
                name              string 
		server            *httptest.Server // server to use
		netDial           func(network, addr string) (net.Conn, error)
		netDialContext    func(ctx context.Context, network, addr string) (net.Conn, error)
		netDialTLS        func(network, addr string) (net.Conn, error)
		netDialTLSContext func(ctx context.Context, network, addr string) (net.Conn, error)
		tlsClientConfig   *tls.Config
	}{
		 name: "HTTP server, all NetDial* defined, shall use NetDialContext",
	         server: server,
                 …
		
```

**Comment by lluiscampos** [comment]
Thanks @garyburd for your feedback. I updated now the pull request following your suggestion. I updated the commit message accordingly too.

> * Remove DialTLS field.  The corresponding field in net/http Transport is deprecated, so there's no need to add it here.

As `Dialer` already had `Dial` and `DialContext` I thought it was good to add the two... but being this a new field, makes sense not to add the deprecated one.

> 
>     * Convert map of tests to slice of tests for consistency with other tests.

Roger that :+1:

**Comment by garyburd** [comment]
Thank you for your contribution.  👍 for the included test.

**Pull request merged**
