### PR TITLE
Add check for Sec-WebSocket-Key header

### PR DESCRIPTION
**Pull request by hirasawayuki**
Fixes issue: #617

Added the following two fixes
- Check that Sec-websocket-key is encoded as base64
- Check that Sec-Websocket-Key is encoded from 16 bytes long

[RFC6455](https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.1) states the following:
> A |Sec-WebSocket-Key| header field with a base64-encoded value that, when decoded, is 16 bytes in length.

### CODE REVIEW

**Comment by garyburd** [comment]
Do popular libraries for other programming languages reject invalid keys?  I don't want this package to the only library that rejects invalid keys. 

Assuming that it's common practice to reject invalid keys, please move the logic to new function `isValidChallengeKey(s string) bool { }` in  [util.go](https://github.com/gorilla/websocket/blob/2d6ee4c55cc9e9dc0eb5929f32a999213e25256f/util.go#L33).  I want to keep the functionality related to keys in one file. 

It's OK to return a single error message for invalid keys.

**Comment by hirasawayuki** [comment]
@garyburd 
Thanks for the review! I checked the [ws(nodejs library)](https://github.com/websockets/ws), and it seems to return HTTP Status 400 if it doesn't match `/^[+/0-9A-Za-z]{22}==$/`. 
So I saw no problem in rejecting an invalid key.

https://github.com/websockets/ws/blob/5edf1f4a1b1750109c1bb56eff7ad78902eee7dc/lib/websocket-server.js#L18
https://github.com/websockets/ws/blob/5edf1f4a1b1750109c1bb56eff7ad78902eee7dc/lib/websocket-server.js#L236-L245

**Comment by garyburd** [comment]
LGTM. 

The nodejs library provides strong evidence that the check is OK, but I want check more libraries before accepting the PR.  One cause for concern is that the  [Autobahn|Testsuite](https://github.com/crossbario/autobahn-testsuite)  does not test invalid keys.

**Comment by plasticsax** [comment]
Simplify: `return err == nil && len(decoded) == 16`

**Comment by hirasawayuki** [comment]
@garyburd
I'll let you be the judge! 😃 

@plasticsax
Thankyou! I fixed it.(3ae5d9c)

**Comment by andrewhodel** [comment]
There is a maximum limit of the incoming data per the base64 limit. 

You should add an error from the upgrader if the size is exceeded for two reasons:

1. The response isn't unknowingly handled in the module code like go's http 301 when there is a .. in the url path. 

2. The developer gets to decide how strict to be instead of a lower level structure that doesn't participate in these cost decisions.

**Comment by andrewhodel** [comment]
The base64 alphabet has a limit per byte with regards to representation size.

**Pull request merged**
