### PR TITLE
Return write buffer to pool on write error

### PR DESCRIPTION
**Pull request by ghost**
Fix bug where connection did not return the write buffer to the pool
after a write error. Add test for the same.

Bonus improvement: Adjust message and buffer size in TestWriteBufferPool
to test that pool works with fragmented messages.

### CODE REVIEW

**Comment by kisielk** [comment]
Would it make more sense to put this cleanup code in a defer?

**Comment by stevenscott89** [comment]
@kisielk After looking into your suggestion, I realized that I missed another error case.  The code belongs in messageWriter.fatal.  That method should be renamed to finishWrite for symmetry with the existing prepWrite method. I'll push a change later today.

**Comment by kisielk** [comment]
Another thing is, should `c.writer` be set to `nil` on error as well, like it is on final, or does that not matter?

**Comment by stevenscott89** [comment]
Please look again.  

The messageWriter.fatal method contained the code to cleanup after a message. I moved the buffer cleanup to that method and renamed the method to endMessage to make the intent of the method clearer.

I also renamed Conn.prepMessage to beginMessage for symmetry with endMessage. I also moved some duplicated code at the beginMessage call sites to beginMessage.

**Pull request merged**
