### PR TITLE
Permessage-deflate compression support.

### PR DESCRIPTION
**Pull request by euforia**

### CODE REVIEW

**Comment by garyburd** [comment]
I pulled the PR to my workstation and I am addressing a few issues.  Thanks!

**Comment by reeze** [comment]
Any progress ? :)

**Comment by garyburd** [comment]
Some.  See https://github.com/garyburd/websocket/tree/pmce

**Comment by reeze** [comment]
Thanks for you & @euforia 's work!

**Comment by riaan53** [comment]
Hi,

Any update on this? 

Thanks!
Riaan

**Comment by dcelasun** [comment]
Any progress?

**Comment by riaan53** [comment]
I see the people at datatog has also done some work on this - havnt tested it yet. https://github.com/DataDog/websocket/tree/compression

**Comment by y3llowcake** [comment]
Any updates on this PR or gary's pmce branch? I'm quite interested in this feature and willing to help out if there is work to be done.

**Comment by garyburd** [comment]
This PR is the basis for work in another PR.  See https://github.com/gorilla/websocket/issues/3 for work remaining.

**Pull request closed without merging**
