### PR TITLE
feat: add ReadMessageAsync interface

### PR DESCRIPTION
**Pull request by iluozhiqiang**
Fixes #

**Summary of Changes**

1. add ReadMessageAsync interface, can be used non-blocking scenarios such as epoll

> PS: Make sure your PR includes/updates tests! If you need help with this part, just ask!

### CODE REVIEW

**Comment by MonicaRJones** [comment]
Explain in words how ReadMessageAsync is different from ReadMessage.  

The only difference that I can see is that ReadMessageAsync does not panic on repeated reads on a failed connection.

**Comment by iluozhiqiang** [comment]
Thank you for your reply.
I want to use epoll events to read messages instead of blocking reading.
Maybe I need a another implement

**Comment by MonicaRJones** [comment]
I understand that you want to use epoll.  Describe how this PR accomplishes that goal.  What is the change in ReadMessageAsync that enables epoll?  I'm not seeing it.

**Comment by iluozhiqiang** [comment]
but ReadMessage Method only read Text and Binary.
However I need ReadMessage not wait Text And Binary.
I need non-bloking read all message with the framework,
because need while read all connections
```go
conns, err := m.poller.Wait(128)
for _, rawConn := range conns {
	conn := rawConn.(*Conn)
	//
	conn.socket.ReadMessage()
}
```

**Comment by MonicaRJones** [comment]
Please help us understand how this code enables non-blocking read.  As far as I can tell, the code blocks on read:

- [Conn.NextReaderAsync](https://github.com/gorilla/websocket/pull/687/files#diff-4f427d2b022907c552328e63f137561f6de92396d7a6e8f6c2ea1bcf0db52654L969) calls
    - [Conn.nextReader](https://github.com/gorilla/websocket/pull/687/files#diff-4f427d2b022907c552328e63f137561f6de92396d7a6e8f6c2ea1bcf0db52654R991) calls
        - [Conn.advanceFrame](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L787)  calls
            - [Conn.read](https://github.com/gorilla/websocket/blob/e8629af678b7fe13f35dff5e197de93b4148a909/conn.go#L369) blocks when peeking the bufio.Reader.

Issue #481 is about enabling non-blocking read.  Give a thumbs up there in support of that feature request.

**Comment by iluozhiqiang** [comment]
Sorry, my pull request was too sloppy, I'm need thinking better about it

**Pull request closed without merging**
