### PR TITLE
Add links for alternative libraries into README.md

### PR DESCRIPTION
**Pull request by nhooyr**
Updates #543

### CODE REVIEW

**Comment by nhooyr** [comment]
@elithrar I know you wanted one liners but I figured since I'd have to point out that golang.org/x/net/websocket is deprecated, might as well have a one liner for mine and gobwas/ws.

**Comment by nhooyr** [comment]
@elithrar Could you please merge this.

**Comment by srybacki** [comment]
I don't see why this package should list other packages, but if it does, this package should not give opinions about those other packages. Let people judge for themselves.

**Comment by nhooyr** [comment]
Fair enough. Fixed.

**Comment by nhooyr** [comment]
> I don't see why this package should list other packages

This package is the hub for WebSocket's and Go so its nice to list other packages that may fit peoples needs better or just to be more aware of the ecosystem. Some previous discussion at https://github.com/gorilla/websocket/pull/543

**Comment by nhooyr** [comment]
Someone else feel free to pick this up if desired. I'm going to abandon it for now.

**Pull request closed without merging**
