### PR TITLE
refine Conn.SetReadDeadline

### PR DESCRIPTION
**Pull request by sunlei99**
Under my circumstance

I want to use the websocket connection **Half-duplex**

e.g.
```go
    conn, _ := upgrader.Upgrade(w, r, nil)
    for {
        conn.SetReadDeadline(time.Now().Add(time.Second * 3))
        err := c.Conn.ReadJSON(&p)
        // do something...
        if err != nil && strings.Contains(err.Error(), "i/o timeout") {
            // read timeout do something
        } else if err == nil {
            // parse the data from client
        } else {
            // process the other err
        }
    }
```

**but** 
 **readErr** of Conn is always not nil after the first read timeout so the code above will panic due to 
the code in Conn.NextReader
```go
func (c *Conn) NextReader() (messageType int, r io.Reader, err error) {
        ...
        // always not nil after first timeout
	for c.readErr == nil {
		...
	}

	// panic...
	c.readErrCount++
	if c.readErrCount >= 1000 {
		panic("repeated read on failed websocket connection")
	}

	return noFrame, nil, c.readErr
}
```

### CODE REVIEW

**Comment by garyburd** [comment]
This PR does not handle the case where the timeout happens after one byte of a message is read.

Use a goroutine.

**Comment by sunlei99** [comment]
Does that mean the connection is not available and should be abandoned after the timeout set by 
SetReadDeadline?  

The function SetReadDeadline should only be called ONCE?

Under the circumstance above, the only way is invoking a new goroutine?

**Comment by garyburd** [comment]
The connection should be closed and abandoned after any error, including timeout.

Most applications that call SetReadDeadline with a non-zero time will call SetReadDeadline multiple times.  

Use time.Ticker time.After, goroutines, etc. to execute code at specified times.

**Comment by sunlei99** [comment]
@garyburd thanks!

    About the second question: The function SetReadDeadline should only be called ONCE?

readErr of Conn is always not nil after the first read timeout, which is set by SetReadDeadline.
So does it means that 
The function SetReadDeadline should only be called ONCE?

**Comment by garyburd** [comment]
If an application calls SetReadDeadline at all,, then it's typical to call the method multiple times.

**Comment by sunlei99** [comment]
@garyburd Yes! I intended to call the method multiple times.
but the program will panic, because conn.readErr is always not nil 

```go
    conn, _ := upgrader.Upgrade(w, r, nil)
    for {
        conn.SetReadDeadline(time.Now().Add(time.Second * 3))
        err := conn.ReadJSON(&p)
        // do something...
        if err != nil && strings.Contains(err.Error(), "i/o timeout") {
            // read timeout do something
        } else if err == nil {
            // parse the data from client
        } else {
            // process the other err
        }
    }
```


but
readErr of Conn is always not nil after the first read timeout so the code above will panic due to
the code in Conn.NextReader
```go
func (c *Conn) NextReader() (messageType int, r io.Reader, err error) {
        ...
        // always not nil after first timeout
	for c.readErr == nil {
		...
	}

	// panic...
	c.readErrCount++
	if c.readErrCount >= 1000 {
		panic("repeated read on failed websocket connection")
	}

	return noFrame, nil, c.readErr
}
```

**Comment by garyburd** [comment]
SetReadDeadline can be called multiple times to extend deadlines, but the method can only be called once for a given read operation.

Use time.Ticker time.After, goroutines, etc. to execute code at specified times.

**Pull request closed without merging**
