### PR TITLE
Support http proxy correctly

### LINKED ISSUE #892: Why does specifying the proxy address not work?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there.
I want to specify proxy address for websocket connection instead of  setting environment variables `http_proxy` and `https_proxy`. I copied code from[#107 ](https://github.com/gorilla/websocket/issues/107) and it's like:

```golang
dg.Dialer = &websocket.Dialer{
  Proxy: http.ProxyURL(&url.URL{
	  Scheme: "http", // or "https" depending on your proxy
	  Host:   "localhost:7890",
  }),
}
```
I have also tried to use `https`  but it still doesn't work.  However,  if use `http_proxy` and `https_proxy` env variables  with `http.ProxyFromEnvironment`, it works fine. code snippet：

```golang
os.Setenv("http_proxy", "http://localhost:7890")
os.Setenv("https_proxy", "http://localhost:7890")
os.Setenv("HTTP_PROXY", "http://localhost:7890")
os.Setenv("HTTPs_PROXY", "http://localhost:7890")
dg, err := discordgo.New("Bot " + botToken)
dg.Dialer = &websocket.Dialer{
   Proxy: http.ProxyFromEnvironment,
}
```

### Expected Behavior

I want to specify proxy address for websokct addres instead of setting environment variables http_proxy and https_proxy. Because it affects other http connection that don't want to go through the proxy. 

### Steps To Reproduce

_No response_

### Anything else?

I am using [discordgo](https://github.com/bwmarrin/discordgo) which uses this repo inside. So it maybe not a right place to open the issue here. Hope someone could explain why setting proxy for `Dialer` does not work as I expect.

### PR DESCRIPTION
**Pull request by 134130**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Go Version Update
- [ ] Dependency Update

## Description
- Currently, the `gorilla/websocket`'s HTTP Proxy implementation is only supports `CONNECT` proxy, which can be called as "Tunnel Proxy".
- But there is another HTTP Proxy:
  - At the TCP level, the request is made to the Proxy address.
  - But the Host in the HTTP request is different.
- Typically, the `HTTP_PROXY` environment variable works as later one, and the `HTTPS_PROXY` environment variable works as "Tunnel Proxy".
  - Many applications, including `curl` and `go http client`, follow this behavior.
  - So there is a reason, why #892 is issued.
- I have referenced the golang's http/transport implementation: https://github.com/golang/go/blob/master/src/net/http/transport.go#L1744

## Related Tickets & Documents

- Closes #892

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests
 
## Run verifications and test

- [ ] `make verify` is passing
- [ ] `make test` is passing
> No Makefile I can find. I have tested with `go test ./...`
> Also, I have wrote the integration tests like this: https://github.com/134130/websocket/blob/proxy-test/proxy_test.go

### CODE REVIEW

**Comment by 134130** [comment]
I want to make another PR which closes https://github.com/gorilla/websocket/issues/739 after this Pull Requests is merged.
@gorilla/pull-request-reviewers can you review this PR?

**Comment by 134130** [comment]
ping

**Comment by canelohill** [comment]
This PR changes how the package connects to HTTP proxies.  Can this PR break applications that use HTTP proxies, or do all proxies support both modes (CONNECT vs no CONNECT)?

**Comment by adrianosela** [comment]
Hey folks, can we add to this work to allow providing client certificates and also means to override the server's CA cert pool? I assume plenty of folks out there (me included) use mTLS certificates for HTTPS proxy authentication.

**Comment by jaitaiwan** [comment]
We need Canelohills question averted before we can decide next steps.

**Comment by adrianosela** [comment]
Maybe as a quick work-around to unblock those of us waiting for this change, we can just turn the private function `proxy_RegisterDialerType` function into a public one (`RegisterDialerType`)  and allow folks to register their own custom scheme dialers...

I've done that in a local (vendored) copy of this repo and I am able to register my custom dialer for "https" and got it to work.

For @134130, here's some code that does what my dialer does... if anything for inspiration 😄:

```

func getTcpConnOverHttpsProxy(
	target string,
	clientCert tls.Certificate,
        proxyCertPool *x509.CertPool,
) (net.Conn, error) {
	host, _, err := net.SplitHostPort(target)
	if err != nil {
		return nil, fmt.Errorf("failed to parse host from target address: %v", err)
	}

	tcpToProxy, err := net.Dial("tcp", target)
	if err != nil {
		return nil, fmt.Errorf("failed to establish tcp connection to proxy: %v", err)
	}

	tlsToProxy := tls.Client(tcpToProxy, &tls.Config{
		ServerName:   host,
		Certificates: []tls.Certificate{clientCertificate},
		RootCAs:      proxyCertPool,
	})

	if err = tlsToProxy.Handshake(); err != nil {
		tlsToProxy.Close()
		return nil, fmt.Errorf("failed to establish tls connection to proxy: %v", err)
	}

	connectReq := fmt.Sprintf("CONNECT %s HTTP/1.1\r\nHost: %s\r\n\r\n", target, host)
	if _, err = tlsToProxy.Write([]byte(connectReq)); err != nil {
		tlsToProxy.Close()
		return nil, fmt.Errorf("failed to write CONNECT http request to proxy: %v", err)
	}

	response, err := http.ReadResponse(bufio.NewReader(tlsToProxy), &http.Request{Method: "CONNECT"})
	if err != nil {
		tlsToProxy.Close()
		return nil, fmt.Errorf("failed to read response for CONNECT http request to proxy: %v", err)
	}

	if response.StatusCode != http.StatusOK {
		tlsToProxy.Close()
		return nil, fmt.Errorf("failed to establish CONNECT tunnel to proxy, got status code: %d", response.StatusCode)
	}

	tcpToTarget := tlsToProxy

	return tcpToTarget, nil
}
```

**Comment by 134130** [comment]
> Hey folks, can we add to this work to allow providing client certificates and also means to override the proxy server's CA cert pool? I assume plenty of folks out there (me included) use mTLS certificates for HTTPS proxy authentication.

I thought the PR is large enough.

As I wrote above, the next PR will support TLS between client and proxy. Thanks!

**Comment by canelohill** [comment]
@adrianosela  I removed `proxy_RegisterDialerType` from this package.  The function is replaced by [proxy.RegisterDialerType](https://pkg.go.dev/golang.org/x/net/proxy#RegisterDialerType).

**Comment by jaitaiwan** [comment]
Alright, now I'm lost :sweat_smile: where are we at now?

**Comment by 134130** [comment]
> This PR changes how the package connects to HTTP proxies. Can this PR break applications that use HTTP proxies, or do all proxies support both modes (CONNECT vs no CONNECT)?

@canelohill 

Sorry for the lack of explanation. The PR makes both of CONNECT and No CONNECT Proxy mode support.
- AS IS: `gorilla/websocket` always tries "CONNECT Proxy", even if "No CONNECT Proxy" is correct.
- Now: `gorilla/websocket` correctly choose the Proxy mode.

**Comment by 134130** [comment]
> @adrianosela I removed `proxy_RegisterDialerType` from this package. The function is replaced by [proxy.RegisterDialerType](https://pkg.go.dev/golang.org/x/net/proxy#RegisterDialerType).

IMO, `gorilla/websocket` should support default proxy modes as it's battery, and should not have behaviour that conflicts with golang's `net/http`, not something users to make implement.

**Comment by canelohill** [comment]
@134130 Your comments do not address my question. 

Can this PR break an application that is currently using an HTTP proxy?  This is a different question from what the package should do. 

Did you test the change with popular proxies?

**Comment by 134130** [comment]
| - | MITM Proxy | Fiddler | Burp Suite | [goproxy](https://github.com/elazarl/goproxy) | [gomitmproxy](https://github.com/AdguardTeam/gomitmproxy) | 
|--------|--------|--------|--------|----|----|
| Before (HTTP) | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Before (HTTPS) | ✅ | ✅ | ✅ | ✅ | ✅ | 
| After (HTTP) | ✅ | ✅ | ❌  | ✅ | ✅ | 
| After (HTTPS) | ✅ | ✅ | ✅ | ✅ | ✅ | 

Oops, Sorry. Burp Suite will be broken with these changes. 

I've thought many client libraries are using No-Connect method for non-websocket requests (including SSE), and It looks weird to me, and these changes is needed.

I think this PR is no need to merged. I'll make another PR which closes: #739. Sorry for wasting your time.

**Comment by canelohill** [comment]
I suspected that this PR would not work on a proxy server in the wild because the WebSocket protocol use full-duplex data transmission.

The HTTP protocol (and SSE layered on HTTP) uses half-duplex data transmission.  The websocket protocol will not work through a proxy that assumes that all data transmission is half-duplex. 

The CONNECT method tells the proxy to get out of the way and just copy the data back and forth.

**Pull request closed without merging**
