### PR TITLE
Add SetEscapeHTML into json.

### PR DESCRIPTION
**Pull request by asuleymanov**
Processing of HTML tags in the message sent by json is added.

### CODE REVIEW

**Comment by adamdecaf** [comment]
Thanks for the contribution!

`SetEscapeHTML` only exists in Go 1.7+, so the older builds are failing. I need to remember what the support policy for old Go versions on this project is, but I'd rather not add a branch in the code. 

Re-reading the go docs on this reads as it's backwards compatible too.

**Comment by elithrar** [comment]
Would this change embedded (implicit /API behavior) expectations about the
output of WriteJSON?

That may introduce problems for those expecting otherwise.

Could we expose a JSONEncoder field, or option on *Conn, to supply your own
encoder?

Users could also just override the behavior of WriteJSON with their own
implementation of *Conn, since none of the methods it calls internally are
private.

**Comment by stevenscott89** [comment]
This change could create security vulnerability in an existing application.  It seems wise to keep the "safe" default.

**Comment by garyburd** [comment]
Closing for reasons stated in previous comments:

- The "safe" encoding should be retained.
- Applications can use their own encoding function instead of WriteJSON.

**Pull request closed without merging**
