### PR TITLE
Replaced the deprecated ioutil package

### PR DESCRIPTION
**Pull request by enkeyz**
Replaced usage of deprecated `ioutil` functions with their correct ones.

More info why `ioutil` got deprecated: https://go.dev/doc/go1.16

### CODE REVIEW

**Comment by enkeyz** [comment]
I made a mistake and not looking the `go.mod` version: the project should be at least go version 1.16 to use the new functions. Any plans to bump the version to even 1.18?

**Comment by garyburd** [comment]
> Any plans to bump the version to even 1.18?

The package should work with the [supported versions of Go](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance).   You can bump the go.mod file up to 1.16.

**Comment by amustaque97** [comment]
@enkeyz just a follow-up — are you still working on the PR?

**Comment by coreydaley** [comment]
Superseded by https://github.com/gorilla/websocket/pull/840

**Pull request closed without merging**
